version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://todo:todo@db:5432/todo
      SECRET_KEY: dev-secret-key
      DEBUG: '1'
      ALLOWED_HOSTS: 127.0.0.1,localhost
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate && gunicorn todo_project.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://127.0.0.1:8000/login" ]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  db_data:

